var arrLang={
    'english':{
        'Home' : 'Home',
        'About' : 'About',
        'AboutCompany' : 'About Company',
        'DecisionEstablish':'Decision to establish Company',
        'Branches':'Branches',
        'Projects':'Projects',
        'Archives':'News Archives',
        'Vision':'Vision And Mission',
        'Organozational':'Organozational Structure',
        'Achievements':'Achievements',
        'Awareness':'Awareness',
        'AwarenessMethod':'Awareness Methodology',
        'Kids':'Kids Corner',
        'You':'For You',
        'Quality':'Quality of water',
        'purification':'Drinking Water purification',
        'Laboratory':'Central Laboratory',
        'Tenders':'Tenders',
        'TendersComapny':'All Tenders available in the comapny',
        'WasteWater':'Waste Water',
        'WasteWaterTreatment':'Waste Water Treatment',
        'disposalWastewater':'The importance of safe disposal of Waste Water',
        'RawaWstewater':'Raw waste water treatment and types of treatment stations',
        'maintainingWastewater':'The importance of maintaining the waste water network',
        'roleIndustrialWastewater':'The role of the industrial waste water department ',
        'industrialWastewater':'Industrial waste water',
        'Traning':'Traning',
        'TraningType':'Types of traning and halls',
        'SchoolResult':'School Result',
        'Careers':'Careers',
        'Competitions':'Competitions and Jobs',
        'CompetitionsResults':'Competitions Results',
        'Services':'Services',
        'BillInquire':'Bill Inquire',
        'CustomerService':'Customer Service',
        'CustomerCharter':'Customer Charter',
        'ServiceGuide':'Service guide',
        'stepsContract':'Customer steps to contract a service request',
        'SubmitRequest':'Submit a Request',
        'SubmitComplaint':'Submit a Complaint',
        'IntegritySupport':'Integrity Support',
        'briefIntegritySupport':'Brief about Integrity Support',
        'importantIntegritySupport':'The most important work to Integrity Support',
        'FunctionalBehaviour':'Functional behaviour',
        'Photo':'Photo Gallery',
        'ChairmanTour':'Chairman of the board tours',
        'companyLabo':'Company Laboratories',
        'WastewaterStations':'Waste water stations',
        'TraningCenter':'Traning Center',
        'ITSector':'Information technology sector',
        'TechnicalSchool':'Technical school',
        'SSportActivities':'Sport activities'
    },
    'arabic':{
        'Home' : 'الرئيسيه',
        'About' : 'عن الشركه',
        'AboutCompany' : 'نبذة عن الشركه',
        'DecisionEstablish':'قرار إنشاء الشركه',
        'Branches':'فروع الشركه',
        'Projects':'مشروعات الشركه',
        'Archives':'أرشيف الشركه',
        'Vision':'الرؤيه والرساله',
        'Organozational':'الهيكل التنظيمي',
        'Achievements':'إنجازات الشركه',
        'Awareness':'التوعيه و الاتصال',
        'Kids':'ركن الاطفال',
        'You':'لك انت',
        'Quality':'جودة المياه',
        'purification':'تنقية مياه الشرب',
        'Laboratory':'المعمل المركزي لمياه الشرب',
        'Tenders':'المناقصات',
        'TendersComapny':'جميع المناقصات الموجوده في الشركه',
        'WasteWater':'الصرف الصحي',
        'WasteWaterTreatment':'معالجه الصرف الصحي',
        'disposalWastewater':'تعريف بأهميه التخلص من الصرف الصحي',
        'RawaWstewater':'معالجه الصرف الصحي الخام وأنواع محطات المعالجه',
        'maintainingWastewater':'أهميه الحفاظ علي شبكه الصرف الصحي',
        'roleIndustrialWastewater':'دور إداره الصرف الصحي',
        'industrialWastewater':'الصرف الصحي الصناعي',
        'Traning':'التدريب',
        'TraningType':'أنواع التدريب والقاعات',
        'SchoolResult':'نتائج المدرسه',
        'Careers':'وظائف',
        'Competitions':'مسابقات و وظائف',
        'CompetitionsResults':'نتائج المسابقات',
        'Services':'خدمات',
        'BillInquire':'استعلم عن فاتورتك',
        'CustomerService':'خدمه العملاء',
        'CustomerCharter':'ميثاق المتعاملين',
        'ServiceGuide':'دليل الخدمات',
        'stepsContract':'رحله المتعامل للتعاقد علي طلب خدمه',
        'SubmitRequest':'تقديم طلب',
        'SubmitComplaint':'تقديم شكوي',
        'IntegritySupport':'دعم النزاهه',
        'briefIntegritySupport':'نبذه عن إداره دعم النزاهه',
        'importantIntegritySupport':'أبرز أعمال دعم النزاهه',
        'FunctionalBehaviour':'السلوك الوظيفي',
        'Photo':'معرض الصور',
        'ChairmanTour':'جولات رئيس مجلس الإداره',
        'companyLabo':'معامل الشركه',
        'WastewaterStations':'محطات الصرف الصحي',
        'TraningCenter':'مركز التدريب',
        'ITSector':'قطاع تكنولوجيا المعلومات',
        'TechnicalSchool':'المدرسه الفنيه',
        'SportActivities':'النشاط الاجتماعي'
    }
};

$(function(){
    $('.translate').click(function(){
        var lang = $(this).attr('id');
        $('.lang').each(function(index,element){
            $(this).text(arrLang[lang][$(this).attr('key')]);
        });
    });
});